function displayRandomText() {
    const motivationalQuotes = [
        "Practice makes progress.",
        "Every expert was once a beginner.",
        "Small improvements every day lead to big results.",
        "Speed comes from consistency, not rushing.",
        "Your future self will thank you for practicing today.",
        "Focus on accuracy first; speed will follow.",
        "Success is the sum of small efforts repeated daily.",
        "You don't have to be great to start, but you have to start to be great.",
        "The more you practice, the luckier you get.",
        "One more session, one step closer to mastery.",
        "Discipline beats motivation when motivation fades.",
        "Mistakes are proof that you are learning.",
        "Progress is progress, no matter how small.",
        "Every keystroke builds muscle memory.",
        "The keyboard rewards persistence.",
        "A slow start can lead to a fast finish.",
        "Your only competition is who you were yesterday.",
        "Train your fingers, sharpen your mind.",
        "Consistency creates confidence.",
        "The path to mastery is repetition.",
        "You are stronger than your excuses.",
        "Every minute of practice compounds over time.",
        "Typing fast starts with typing correctly.",
        "Stay patient; improvement is happening.",
        "Growth begins outside your comfort zone.",
        "Focus on the process, not the outcome.",
        "Champions are built through daily habits.",
        "Success is earned one practice session at a time.",
        "A goal without action remains a wish.",
        "Believe in the power of steady progress.",
        "The best investment is in your own skills.",
        "Your effort today becomes your strength tomorrow.",
        "Stay committed to your goals.",
        "Hard work turns potential into achievement.",
        "You are capable of more than you think.",
        "Every challenge is an opportunity to improve.",
        "Keep showing up; that's where success begins.",
        "Mastery is built one repetition at a time.",
        "Never underestimate the power of persistence.",
        "The difference between good and great is practice.",
        "Success grows where discipline is planted.",
        "Your determination defines your destination.",
        "Every day is a chance to get better.",
        "Typing faster starts with thinking smarter.",
        "Stay focused and trust the process.",
        "Improvement requires patience and effort.",
        "You are writing your future one key at a time.",
        "Don't stop when you're tired; stop when you're done.",
        "The secret to success is consistency.",
        "Push yourself because no one else can do it for you.",
        "Your limits are often farther away than they appear.",
        "Confidence comes from preparation.",
        "Great things take time.",
        "Every practice session matters.",
        "Success starts with showing up.",
        "Keep moving forward, even if it's one step at a time.",
        "Learning never exhausts the mind.",
        "A little progress each day adds up.",
        "Stay hungry for improvement.",
        "The journey of a thousand miles begins with a single step.",
        "Your keyboard is a tool; mastery is the goal.",
        "Persistence breaks resistance.",
        "Train hard today, type faster tomorrow.",
        "Nothing worth having comes easy.",
        "Keep your eyes on the goal.",
        "The strongest habits are built through repetition.",
        "Every mistake teaches a lesson.",
        "You become what you repeatedly practice.",
        "Great achievements are built from daily actions.",
        "The best way to predict your future is to create it.",
        "Stay dedicated to your growth.",
        "Effort is never wasted.",
        "The road to excellence is always under construction.",
        "Practice turns uncertainty into confidence.",
        "Your progress is your reward.",
        "Focus, type, improve, repeat.",
        "Winning starts with preparation.",
        "Every second spent practicing counts.",
        "Skill is earned, not given.",
        "The harder you work, the easier it becomes.",
        "Keep striving for better.",
        "Your goals deserve your effort.",
        "A champion is simply someone who never gave up.",
        "The key to mastery is patience.",
        "Every day is another chance to improve.",
        "Stay positive, stay persistent.",
        "The future belongs to those who prepare today.",
        "Your potential is limitless.",
        "Progress is built on persistence.",
        "Success loves consistency.",
        "One more word. One more sentence. One more improvement.",
        "Typing is not just speed; it's precision and confidence.",
        "Trust your training.",
        "The best time to improve is now.",
        "Keep practicing until it becomes second nature.",
        "Excellence is a habit, not an act.",
        "You are closer than you think.",
        "Stay focused on the next improvement.",
        "Every session is a step toward mastery.",
        "The journey is difficult, but the destination is worth it."
    ];

    const typingGoals = [
        "Improve typing accuracy to 95% or higher",
        "Reach 40 WPM consistently",
        "Reach 60 WPM consistently",
        "Reach 80 WPM consistently",
        "Reach 100 WPM consistently",
        "Reduce typing mistakes",
        "Type without looking at the keyboard",
        "Master the home row technique",
        "Build strong finger muscle memory",
        "Improve typing endurance",
        "Develop a steady typing rhythm",
        "Increase speed without sacrificing accuracy",
        "Learn proper finger placement",
        "Use all ten fingers efficiently",
        "Reduce backspacing habits",
        "Become comfortable with punctuation",
        "Type numbers faster and more accurately",
        "Improve capitalization accuracy",
        "Strengthen weak fingers",
        "Improve typing under time pressure",
        "Maintain focus during long typing sessions",
        "Read ahead while typing",
        "Anticipate words before finishing the current one",
        "Increase confidence while typing",
        "Write emails faster",
        "Take notes more efficiently",
        "Improve productivity at work",
        "Improve productivity at school",
        "Prepare for data entry jobs",
        "Prepare for administrative work",
        "Improve coding speed",
        "Type code with fewer mistakes",
        "Improve transcription speed",
        "Become a touch typist",
        "Achieve professional typing speed",
        "Reach elite typing performance",
        "Develop consistent daily practice habits",
        "Complete a typing test without major errors",
        "Improve hand coordination",
        "Increase concentration while typing",
        "Learn keyboard shortcuts",
        "Improve editing efficiency",
        "Reduce hand movement while typing",
        "Type long documents comfortably",
        "Improve reaction time on the keyboard",
        "Type faster during exams",
        "Build confidence for office work",
        "Become more efficient in digital communication",
        "Track and improve typing statistics",
        "Practice typing every day",
        "Stay motivated throughout the learning process",
        "Break through a typing plateau",
        "Reach the top 10% of typists",
        "Reach the top 1% of typists",
        "Type naturally and effortlessly",
        "Transform typing into second nature",
        "Develop speed through accuracy",
        "Master difficult words and vocabulary",
        "Improve consistency across all typing tests",
        "Make typing a lifelong skill"
    ];

    function getRandomQuotes() {
        return motivationalQuotes[
            Math.floor(Math.random() * motivationalQuotes.length)
        ];
    }

    function getRandomGoal() {
        return typingGoals[
            Math.floor(Math.random() * typingGoals.length)
        ];
    }

    document.querySelector(".dashboard-quoteoftheday").textContent = getRandomQuotes();
    document.querySelector(".dashboard-goal").textContent = getRandomGoal();
}